/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBookingLeadRouteImport } from './routes/api.booking-lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingLeadRoute = ApiBookingLeadRouteImport.update({
  id: '/api/booking-lead',
  path: '/api/booking-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/booking-lead': typeof ApiBookingLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/booking-lead': typeof ApiBookingLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/booking-lead': typeof ApiBookingLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/booking-lead'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/booking-lead'
  id: '__root__' | '/' | '/api/booking-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBookingLeadRoute: typeof ApiBookingLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-lead': {
      id: '/api/booking-lead'
      path: '/api/booking-lead'
      fullPath: '/api/booking-lead'
      preLoaderRoute: typeof ApiBookingLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBookingLeadRoute: ApiBookingLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
